import "~/styles/globals.css";

import { type Metadata } from "next";
import { Comfortaa } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "~/trpc/react";
import { LearnNavbar } from "./_components/learn-navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-comfortaa",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${comfortaa.variable}`}>
        <body className="bg-brand-primary font-sans text-white">
          <LearnNavbar />
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
